eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8300